### ISSUE TITLE
Is it possible to make this undetected again?

### ISSUE THREAD

**Issue by GlennFTW** [helloobaby/alwayslose#1]
What would I have to do to make this undetected?

**Comment by Inverse25k** [comment]
change hook ig

**Comment by Inverse25k** [comment]
no

**Comment by Inverse25k** [comment]
not only an injector makes it ud

**Comment by helloobaby** [comment]
i know, this is the easiest way.
At least you have to hide the hook，and the hide illegal memory page and modules.And digital signature，hide from enum thread or process,callstack trace,and many methods

**Comment by Inverse25k** [comment]
ye but just using a ud injector won't do shit u can last longer then with a detected one of course but still even then

**Comment by helloobaby** [comment]
yeah

**Comment by GlennFTW** [comment]
Use brain
