### ISSUE TITLE
自瞄失效

### ISSUE THREAD

**Issue by H3artdown** [helloobaby/alwayslose#11]
因为闲来无事研究起了远古版本ayy 参考了您的资料修复了所有功能以后发现即便更换了最新的offset 我的自瞄还是没有效果
想请教一下 如果方便的话可以留一个您的联系方式吗

**Comment by helloobaby** [comment]
qq917893201&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "helloobaby/alwayslose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月29日(星期四) 晚上6:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[helloobaby/alwayslose] 自瞄失效 (#11)





 
因为闲来无事研究起了远古版本ayy 参考了您的资料修复了所有功能以后发现即便更换了最新的offset 我的自瞄还是没有效果
 想请教一下 如果方便的话可以留一个您的联系方式吗
