### ISSUE TITLE
cheat doesnt shoot

### ISSUE THREAD

**Issue by PewCode** [helloobaby/alwayslose#2]
hello, well as the tittle says the cheat doesnt shoot

**Comment by helloobaby** [comment]
autowall is broken now, autoshoot worked correctly, Is that right？

**Comment by PewCode** [comment]
i didnt shoot at all

**Comment by helloobaby** [comment]
can ESP work?

**Comment by PewCode** [comment]
ESP works fine

**Comment by helloobaby** [comment]
try https://github.com/helloobaby/AYYWARE-injector/blob/main/ayyconfig.cfg

**Comment by PewCode** [comment]
it shouldnt be the config i think
because i configure the cheat and it simply doesnt shoot at all

**Comment by helloobaby** [comment]
slient-aim work?

**Comment by PewCode** [comment]
idk

**Comment by helloobaby** [comment]
Legit or Rage,which one are you use?

**Comment by PewCode** [comment]
rage

**Comment by helloobaby** [comment]
are you choose 'Active' and 'Enable' ?

**Comment by PewCode** [comment]
i think so

**Comment by PewCode** [comment]
i enabled rage
and then made my rage settings

**Comment by helloobaby** [comment]
Can you put a picture of your settings  in 'rage'
I'm very weird

**Comment by PewCode** [comment]
sec

**Comment by PewCode** [comment]
![grafik](https://user-images.githubusercontent.com/60573046/119489764-51af0e80-bd5c-11eb-8221-245f05ed796f.png)

**Comment by helloobaby** [comment]
i know why , you can try my configuration(in the same path of csgo.exe).And this project has many bugs  still now, 'Accuracy' - 'Auto Wall' if broken now, if you choose,means not shooting.'Hit Chance','Smart Aim' ,'Position Adjustment ' and also cause the bug。
Don't turn on all settings, some functions are outdated and invalid.

**Comment by PewCode** [comment]
aight how long will it take to fix them?

**Comment by helloobaby** [comment]
idk,haha

**Comment by PewCode** [comment]
i have a idea for u just make your config pre setet easy fix

**Comment by helloobaby** [comment]
what?

**Comment by PewCode** [comment]
config preset
